package com.example.danshal.ui.login

import androidx.lifecycle.ViewModelProvider
import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import com.example.danshal.databinding.RegisterFragmentBinding
import android.text.SpannableString
import android.text.Spanned
import android.text.method.LinkMovementMethod
import android.text.style.ClickableSpan
import android.util.Log
import android.util.Patterns
import android.widget.TextView
import android.widget.Toast
import androidx.navigation.fragment.findNavController
import com.example.danshal.R
import com.example.danshal.models.Address
import com.example.danshal.models.User
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.ktx.auth
import com.google.firebase.firestore.ktx.firestore
import com.google.firebase.ktx.Firebase


class RegisterFragment : Fragment() {

    lateinit var textView: TextView
    private lateinit var auth: FirebaseAuth

    private lateinit var registerViewModel: RegisterViewModel

    private var _binding: RegisterFragmentBinding? = null
    private val binding get() = _binding!!

    private val db = Firebase.firestore

    private var profileIm = "https://firebasestorage.googleapis.com/v0/b/danshal-c7e70.appspot.com/o/user_images%2Fflat-faces-icons-circle-persona-icon-115628952315akhsf8ncl.png?alt=media&token=9e6dd540-85ab-4ec3-8dff-1b4339c3e76f"

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        registerViewModel =
            ViewModelProvider(this).get(RegisterViewModel::class.java)

        _binding = RegisterFragmentBinding.inflate(inflater, container, false)

        auth = Firebase.auth

        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        binding.btnRegister.setOnClickListener {
            if (validate()){
                createUser(binding.etUsername.text.toString(), binding.etPassword.text.toString())
            }
        }

        createLoginSpan()
    }

    //Creating clickable span
    private fun createLoginSpan() {
        textView = binding.tvLogin
        val text = binding.tvLogin.text.toString()
        val spannableString = SpannableString(text)
        val clickableSpan: ClickableSpan = object : ClickableSpan() {
            override fun onClick(view: View) {
                findNavController().navigate(
                    R.id.action_nav_register_to_nav_login
                )
            }
        }
        spannableString.setSpan(clickableSpan, 16, 23, Spanned.SPAN_EXCLUSIVE_EXCLUSIVE)
        textView.setText(spannableString, TextView.BufferType.SPANNABLE)
        textView.movementMethod = LinkMovementMethod.getInstance()
    }

    private fun validate(): Boolean{
        return if (Patterns.EMAIL_ADDRESS.matcher(binding.etUsername.text.toString()).matches()
            && binding.etPassword.text.toString().isNotBlank()
            && binding.etPassword.text.length > 4
            && binding.etPasswordVal.text.isNotBlank()
            && binding.etName.text.isNotBlank()){
            passwordChecker()
        }else{
            Toast.makeText(this.context, getString(R.string.empty_field), Toast.LENGTH_LONG).show()
            false
        }

    }

    private fun passwordChecker(): Boolean {
        return if (binding.etPassword.text.toString().equals(binding.etPasswordVal.text.toString())){
            true
        }else{
            Toast.makeText(this.context, getString(R.string.wachtwoord_ongelijk), Toast.LENGTH_LONG).show()
            false
        }
    }

    private fun createUser(email: String, password: String) {
        auth.createUserWithEmailAndPassword(email, password).addOnCompleteListener { task ->
            if (task.isSuccessful) {

                //Unique id generated by Firebase
                val id = auth.currentUser?.uid

                //Data inputfields
                val naam = binding.etName.text.toString()
                val adres: Address? = null
                val email = email
                val user = id?.let { User(naam, adres, email, profileIm, it ) }
                // Add a new document with a generated ID
                user?.let {
                    db.collection("users")
                        .document(id)
                        .set(it)
                        .addOnSuccessListener { documentReference ->
                            Log.d("Cloud", "DocumentSnapshot added with ID: $documentReference")
                        }
                        .addOnFailureListener { e ->
                            Log.w("Cloud", "Error adding document", e)
                        }
                }
                findNavController().navigate(
                    R.id.action_nav_register_to_nav_home
                )
                Log.e("Task", "Succes")
            }else{
                Log.e("Task", "Failed..."+task.exception)
            }

        }
    }

    override fun onStart() {
        super.onStart()
        // Check if user is signed in (non-null) and update UI accordingly.
        val currentUser = auth.currentUser
        if(currentUser != null){
            findNavController().navigate(
                R.id.action_nav_register_to_nav_home
            )
        }
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }

}